// Data from https://github.com/dariusk/corpora/tree/master/data

export default [
  'acorn squash',
  'alfalfa sprout',
  'amaranth',
  'anise',
  'artichoke',
  'arugula',
  'asparagus',
  'aubergine',
  'azuki bean',
  'banana squash',
  'basil',
  'bean sprout',
  'beet',
  'black bean',
  'black-eyed pea',
  'bok choy',
  'borlotti bean',
  'broad beans',
  'broccoflower',
  'broccoli',
  'brussels sprout',
  'butternut squash',
  'cabbage',
  'calabrese',
  'caraway',
  'carrot',
  'cauliflower',
  'cayenne pepper',
  'celeriac',
  'celery',
  'chamomile',
  'chard',
  'chayote',
  'chickpea',
  'chives',
  'cilantro',
  'collard green',
  'corn',
  'corn salad',
  'courgette',
  'cucumber',
  'daikon',
  'delicata',
  'dill',
  'eggplant',
  'endive',
  'fennel',
  'fiddlehead',
  'frisee',
  'garlic',
  'gem squash',
  'ginger',
  'green bean',
  'green pepper',
  'habanero',
  'herbs and spice',
  'horseradish',
  'hubbard squash',
  'jalapeno',
  'jerusalem artichoke',
  'jicama',
  'kale',
  'kidney bean',
  'kohlrabi',
  'lavender',
  'leek ',
  'legume',
  'lemon grass',
  'lentils',
  'lettuce',
  'lima bean',
  'mamey',
  'mangetout',
  'marjoram',
  'mung bean',
  'mushroom',
  'mustard green',
  'navy bean',
  'new zealand spinach',
  'nopale',
  'okra',
  'onion',
  'oregano',
  'paprika',
  'parsley',
  'parsnip',
  'patty pan',
  'pea',
  'pinto bean',
  'potato',
  'pumpkin',
  'radicchio',
  'radish',
  'rhubarb',
  'rosemary',
  'runner bean',
  'rutabaga',
  'sage',
  'scallion',
  'shallot',
  'skirret',
  'snap pea',
  'soy bean',
  'spaghetti squash',
  'spinach',
  'squash',
  'sweet potato',
  'tabasco pepper',
  'taro',
  'tat soi',
  'thyme',
  'topinambur',
  'tubers',
  'turnip',
  'wasabi',
  'water chestnut',
  'watercress',
  'white radish',
  'yam',
  'zucchini',
  'apple',
  'apricot',
  'avocado',
  'banana',
  'bell pepper',
  'bilberry',
  'blackberry',
  'blackcurrant',
  'blood orange',
  'blueberry',
  'boysenberry',
  'breadfruit',
  'canary melon',
  'cantaloupe',
  'cherimoya',
  'cherry',
  'chili pepper',
  'clementine',
  'cloudberry',
  'coconut',
  'cranberry',
  'cucumber',
  'currant',
  'damson',
  'date',
  'dragonfruit',
  'durian',
  'eggplant',
  'elderberry',
  'feijoa',
  'fig',
  'goji berry',
  'gooseberry',
  'grape',
  'grapefruit',
  'guava',
  'honeydew',
  'huckleberry',
  'jackfruit',
  'jambul',
  'jujube',
  'kiwi fruit',
  'kumquat',
  'lemon',
  'lime',
  'loquat',
  'lychee',
  'mandarine',
  'mango',
  'mulberry',
  'nectarine',
  'nut',
  'olive',
  'orange',
  'pamelo',
  'papaya',
  'passionfruit',
  'peach',
  'pear',
  'persimmon',
  'physalis',
  'pineapple',
  'plum',
  'pomegranate',
  'pomelo',
  'purple mangosteen',
  'quince',
  'raisin',
  'rambutan',
  'raspberry',
  'redcurrant',
  'rock melon',
  'salal berry',
  'satsuma',
  'star fruit',
  'strawberry',
  'tamarillo',
  'tangerine',
  'tomato',
  'ugli fruit',
  'watermelon',
  'anemone',
  'amaryllis',
  'amaranth',
  'aster',
  'azalea',
  'babys breath',
  'begonia',
  'bellflower',
  'bergamot',
  'bird of paradise',
  'bluebell',
  'bottlebrush',
  'buttercup',
  'camellias',
  'carnation',
  'chrysantemum',
  'columbine',
  'clover',
  'crocus',
  'daisy',
  'dahlia',
  'daffodil',
  'delphinium',
  'edelweiss',
  'primrose',
  'forget me not',
  'foxglove',
  'freesia',
  'gerbera daisy',
  'gladiolus',
  'hibiscus',
  'heather',
  'hyacinth',
  'holly',
  'iris',
  'jasmine',
  'ladys slipper',
  'lavender',
  'lilac',
  'lily',
  'lotus flower',
  'marigold',
  'marjoram',
  'mimosa',
  'narcissus',
  'orange blossom',
  'orchid',
  'peach blossom',
  'peony',
  'petunia',
  'rhododendron',
  'rosemary',
  'roses',
  'sage',
  'snapdragon',
  'sunflower',
  'tansy',
  'thistle',
  'thyme',
  'tulip',
  'violet',
  'water lily',
  'zinnia',
];

