FROM node:10.15.3

# This will probably be overridden by a volume in the docker-compose file

COPY ./src /app/src
COPY ./public /app/public
COPY ./package.json /app/package.json
COPY ./jsconfig.json /app/jsconfig.json
COPY ./yarn.lock /app/yarn.lock

WORKDIR /app

RUN yarn cache clean
RUN yarn install

ENTRYPOINT ["yarn"]
CMD ["start"]
