FROM node:14.16.1

# This will probably be overridden by a volume in the docker-compose file

COPY ./src /app/src
COPY ./public /app/public
COPY ./package.json /app/package.json
COPY ./jsconfig.json /app/jsconfig.json
COPY ./config-overrides.js /app/config-overrides.js
COPY ./yarn.lock /app/yarn.lock
COPY ./.eslintrc /app/.eslintrc
COPY ./.eslintignore /app/.eslintignore

WORKDIR /app

RUN yarn cache clean
RUN yarn install

ENTRYPOINT ["yarn"]
CMD ["start"]
