export const LEFT_DRAWER_QUERY_PARAM = 'leftDrawer';
export const TMP_DRAWER_QUERY_PARAMS = 'tmpDrawer';

export const TMP_DRAWER_ACCOUNT_VALUE = 'account';

export const PERMANENT_DRAWER_DESKTOP_WIDTH = '30%';
export const PERMANENT_DRAWER_MOBILE_WIDTH = '100%';
export const TEMP_DRAWER_DESKTOP_WIDTH = PERMANENT_DRAWER_DESKTOP_WIDTH;
export const TEMP_DRAWER_MOBILE_WIDTH = '100%';
