FROM node:10.15.3

COPY ./src /app/src
# COPY only what we need for plugin
COPY ./public /app/public
COPY ./package.json /app/package.json
COPY ./jsconfig.json /app/jsconfig.json
COPY ./config-overrides.js /app/config-overrides.js
COPY ./yarn.lock /app/yarn.lock

COPY ./plugin/src /app/plugin/src
COPY ./plugin/config /app/plugin/config

WORKDIR /app

ENV INLINE_RUNTIME_CHUNK false

RUN yarn install
CMD yarn run start-plugin